package rs.codecentric.photo_album.exception;

public enum BusinessErrorCode {

	// API
    API_ERROR_GETTING_ALL_PICTURES,
    API_ERROR_MISSING_MANDATORY_MEMBERS,
    API_ERROR_LOADING_COMPANY,
    API_ERROR_LOADING_PICTURE,
    API_ERROR_CREATING_PICTURE,
    API_ERROR_UPDATING_PICTURE,
    API_ERROR_DELETING_PICTURE,
    API_ERROR_LOADING_USER
    
}
